name: Create a Release

on:
  workflow_dispatch:

env:
  NPM_SCOPE: dipa-projekt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ env.NPM_SCOPE }}"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Read package.json
        id: package
        run: |
          content=`cat package.json | tr -d "\n"`
          echo "::set-output name=json::$content"
      - name: Install dependencies
        run: |
          npm ci
          npm run format
          npm run lint
          npm run build
      - name: Create Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{fromJson(steps.package.outputs.json).version}}
          release_name: Release ${{fromJson(steps.package.outputs.json).version}}
          draft: false
          prerelease: false
      - name: Publish NPM-Package
        run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
